### ISSUE TITLE
"Speak Text with Eleven Labs" has a secret stored in it

### ISSUE THREAD

**Issue by kernkraft235** [twilsonco/SiriShortcuts#4]
You left your API key in the shortcut, I am able to generate TTS and do other API calls. Im not sure if that was intentional or not because the account has no custom voices so maybe its some limited key

**Comment by twilsonco** [comment]
Oops! It has no billing setup for it so it caps at four hours if dictation per month. 

Thanks for letting me know. I’ll push a new version and cancel that key.
